[디자인시스템] 1주차 정경진
carrot-stick/design-system pull request #1
Opened 2024-03-15 17:52 UTC by Februaar

## 고민한 점
- Storybook을 사용하는 이유
- 컴포넌트를 문서화하는 개념
- Chakra UI 스타일 코드 구조

## 작업 내용
- Charkra UI 버튼 컴포넌트 생성
- Storybook 연동

2024-03-15 23:32 UTC, bytrustu requested changes
과제를 가장 먼저 빠르게 진행해주셨네요. ✨
과제 요구사힝과 다른 점이 있어 코멘트 드려요.

chakra-ui는 인터페이스 참고사항이며, 활용하는건 아닙니다. 디자인시스템을 직접 구현해보는 과정인 만큼 버튼 컴포넌트를 요구사항에 따라 직접 설계해서 만들어주시면 됩니다!

2024-03-15 23:39 UTC, Februaar commented
앗 다음부턴 헷갈리면 바로 여쭤보겠습니다 🥲

2024-03-17 08:12 UTC, bytrustu approved these changes
첫번째로 과제를 잘 진행해주셨네요. 👍
교육 과정에서 `코드리뷰` 를 고려하고 있진 않지만, 사전과제에서 간단하게 제안드려봐요.

디자인 시스템 주제와는 다르지만, 프로젝트를 진행하시면서 `코드 컨벤션` 은 어떻게 설정하시나요?
eslint, prettier 더 나아가서 husky(git hook)까지는 현업에서도 기본으로 챙긴답니다.

작성한 코드의 규칙이 맞지 않을때, git commit 단계에서 lint, prettier를 체크하고, 프로젝트 전반의 코드 컨벤션을 지킬수 있어요.

[ESLint, Prettier 세팅과 Husky, Lint-Staged 사용하기 🤔](https://velog.io/@lee7198/ESLint-Prettier-%EC%84%B8%ED%8C%85%EA%B3%BC-Husky-Lint-Staged-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)

2024-03-17 08:12 UTC, bytrustu commented on public/index.html
> +<html lang="en">
P2:

html lang property를 통해 브라우저가 어떤 언어로 인식하는지 달라지게 됩니다.
[참고링크](https://codingeverybody.kr/html-lang-%EC%86%8D%EC%84%B1-%EC%98%AC%EB%B0%94%EB%A5%B8-%EC%9D%B4%ED%95%B4%EC%99%80-%EC%82%AC%EC%9A%A9-%EB%B0%A9%EB%B2%95/)

과정에서 UX를 다루고 있기에, 챙겨보시면 좋겠네요.

2024-03-17 08:12 UTC, bytrustu commented on src/components/Button.tsx
> +}
```suggestion
interface ButtonProps extends Pick<CSSProperties, 'backgroundColor'> {
  size?: "small" | "medium" | "large";
  variant?: "solid" | "outline" | "ghost" | "link";
  label: string;
  onClick?: () => void;
}
```

P3:
React에서 제공하는 타입을 활용하면, style요소를 이렇게 타입 정의해 볼수있어요.
덧붙여서 DOM node property도 `HTMLProps<HTMLButtonElement>` 처럼 타입으로 정의 가능하답니다.

2024-03-18 13:01 UTC, merged