[디자인시스템] 3주차 정경진
carrot-stick/design-system pull request #13
Opened 2024-04-03 22:43 UTC by Februaar

###구현내용

**Button 컴포넌트** 
- 'PropsWithChildren'을 활용하여 'children' 속성을 명시적으로 선언
- 'ButtonHTMLAttributes'와 같이 필요한 모듈 직접 import 해서 사용
- 컴포넌트의 요소 상태(hover, focus)에 따라 'backgroundColor'와 'borderColor'를  사용자가 직접 지정하는 방식으로 스타일링 변경
- 스타일 관련 유틸함수 리팩토링 진행하여 가독성 개선
- color 토큰 100-1000으로 범위 수정

**Input 컴포넌트** 
- Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "color">를 사용하여 'InputProps'에서 'size'와 'color' 속성을 제외하여 직접 지정할 수 있도록 함
- 코드의 가독성을 향상시키기 위해, 'size'에 대한 각 속성을 하나씩 복사해서 할당한 것을 스프레드 문법을 사용하여 간결하게 작성

**Select 컴포넌트**
- CSS 속성의 값(width, height)이 명확하지 않을 때 'CSSProperties' 활용
- 점 표기법을 사용해서 명시적으로 부모 컴포넌트 지정
- size, variant를 props로 전달받아 컴포넌트 스타일링
- select 태그 없이 button, i, ul, li 태그를 이용해서 select 컴포넌트 구현
- isOpen, setIsOpen, option, setIsOption 상태를 전역에서 관리하기 위해 'createContext' 함수를 사용해서 컨텍스트 생성

**Flex 컴포넌트** 
- 'FlexContainer' 의 크기를 'padding' 값으로 지정하는 대신 => 'width', 'height'를 직접 지정하도록 수정
- justifyContent, alignItems 직관적으로 보이게 이름 수정
- gap props 추가

**Modal 컴포넌트**
- Backdrop, Header, Body, Footer으로 세분화해서 컴포넌트 구현
- isOpen, onClose 상태를 관리하기 위해 'createContext' 함수를 사용해서 컨텍스트 생성

###고민한 점
**Button 컴포넌트** 
- 컴포넌트 타입에 React.FC 사용 지양 (children을 다루고 있지 않더라도 암시적으로 children을 갖게 됨)

**Input 컴포넌트** 
- 어떤 상황에서 Omit을 사용하는지
=> 아직 개념에 대해 100% 받아드려지진 않음

**Select 컴포넌트** 
-점 표기법(dot notaion) 사용
=> 많은 컴포넌트를 내보낼 때(<Select. 만 입력해도 자동완성으로 그룹핑한 컴포넌트가 나옴) 그리고 디자인 시스템을 구축할 때 매우 유용해보임
- Option 컴포넌트에서 선택된 value 값을 'setOption'에 업데이트 되도록 하였는데, Trigger 컴포넌트에서 값을 렌더링 할 수 없음
=> 'setOption' 에 value 값이 담기지 않는 걸로 예상 됨

**Modal 컴포넌트**
- width, height, position을 지정하고 스타일 상속에 대해서 아직 헷갈려서 따로 정리해보려함

2024-04-04 07:40 UTC, bytrustu commented
@Februaar 
일주일 동안 일정이 잡혀있어서, 리뷰가 늦을수 있겠어요.
최대한 다음주 화요일까지 드려보도록 할게요! 😁

2024-04-08 12:20 UTC, bytrustu requested changes
수고하셨어요!
3주차 과제하시면서 일관성을 지키고자 했던 노력이 눈에 띄네요. 😊

디자인토큰에 대한 정의, Select 기능과 관련하여 리뷰드립니다.

2024-04-08 12:20 UTC, bytrustu commented on src/components/Select/Trigger.tsx
> +          {isOpen ? <ArrowDownIcon /> : <ArrowUpIcon />}
P2:

Select의 Option 아이콘 방향이 아래로만 되어있는 UI 형태가 이상적이지 않을까요?
https://chakra-ui.com/docs/components/select

2024-04-08 12:20 UTC, bytrustu commented on src/styles/theme/sizes.ts
P3:
theme로 정의하는 디자인 토큰은 공용으로 사용되는 값으로만 관리하면 어떨까요?
HTML tag에 활용되는 style은 컴포넌트를 구성하면서 관리하면 좋겠어요.
예를들어 프로젝트 공통의 컨벤션을 정할 수 있는 zIndex도 예시가 되겠죠?
```tsx
const overlay = 1300;
const modal = 1400;
const popover = 1500;
const toast = 1600;
const tooltip = 1700;
const loading = 1800;
export const zIndex = {
  overlay,
  modal,
  popover,
  toast,
  tooltip,
  loading,
};
```

2024-04-08 12:20 UTC, bytrustu commented on src/components/Select/Select.context.tsx
> +    <SelectContext.Provider value={{ isOpen, option, setIsOpen, setOption }}>
P3:
setIsOpen를 직접 전달해주기보다는
사용하는 입장에서 명확하게 생각되려면 어떻게 해야할지 고민해볼까요?

open, close 함수를 각각 만들어서 전달해줘도 되겠구요.
toggle 함수를 만들어서 전달해줘도 좋겠네요.

2024-04-08 12:20 UTC, bytrustu commented on src/components/Modal/Modal.tsx
> +import ModalFooter from "./ModalFooter";
P3:
간단하게 children으로만 전달해주는 역할의 레이아웃 컴포넌트는 모두 Modal.tsx에 작성해주면 어떨까요?
특정 기능을 가진게 아닌데, 파일을 다 분리해두는것도 확인하는 입장에선 좋지만은 않아보이네요!

2024-04-08 12:20 UTC, bytrustu commented on src/components/Modal/Modal.styles.tsx
> +  z-index: 100;
P3: 
zIndex 값도 토큰으로 활용해보면, 전체적인 레이어의 우선순위를 결정하는데 도움 됩니다.

2024-04-08 12:20 UTC, bytrustu commented on src/components/Input/Input.utils.ts
> +};
InputTypeSize, InputColorType은 상수로 보여지네요.
constant의 경우 `코드컨벤션`을 Camel Case로 정하셨을까요?

2024-04-08 12:20 UTC, bytrustu commented on src/components/Select/Select.tsx
> +const Select = ({
P1:

동료 개발자가 Select 컴포넌트를 활용한다면, 선택한 값은 어떻게 확인이 가능할까요?
그리고 초기 값이 있는 경우에는 어떻게 반영해 줄수 있을까요?

구성해주신 컴포넌트 형태가 아래 링크와 비슷하네요.
UI 관심사 분리, style, 일관성 있는 네이밍도 중요하지만 일단 기능은 작동해야 되지 않을까요?
https://www.radix-ui.com/themes/docs/components/select#with-an-icon

2024-04-08 12:20 UTC, bytrustu commented on src/components/Select/OptionList.tsx
P3:
컴포넌트 이름을 prefix로 붙여주셔도 좋겠어요.
지금은 파일수가 적지만 Options 같은 이름으로 여러 폴더에 있다고 생각해보면 어떨까요?

2024-04-08 12:20 UTC, bytrustu requested changes
수고하셨어요!
3주차 과제하시면서 일관성을 지키고자 했던 노력이 눈에 띄네요. 😊

디자인토큰에 대한 정의, Select 기능과 관련하여 리뷰드립니다.

2024-04-08 12:23 UTC, bytrustu commented
@Februaar 
Omit 관련해서 고민을 작성해주셨네요.
Pick, Omit은 어떤 경우에 사용하게 될까요?

2024-04-09 07:24 UTC, Februaar commented on src/components/Select/Trigger.tsx
> +          {isOpen ? <ArrowDownIcon /> : <ArrowUpIcon />}
지금 보니까 많이 어색하네요 ㅎㅎ
제거하도록 하겠습니다 !

2024-04-09 08:01 UTC, Februaar commented on src/components/Modal/Modal.tsx
> +import ModalFooter from "./ModalFooter";
넵 한 파일에서 관리하는게 낫겠네요 👍

2024-04-09 08:09 UTC, Februaar commented on src/components/Input/Input.utils.ts
> +};
PascalCase가 익숙하다보니 네이밍을 Pascal로 작성했는데, 좀 더 일관성있게 수정해야될 것 같아요..

2024-04-09 18:24 UTC, Februaar commented on src/styles/theme/sizes.ts
말씀해주신데로 적용해보겠습니다 !!

2024-04-09 19:03 UTC, Februaar commented on src/components/Select/Select.context.tsx
> +    <SelectContext.Provider value={{ isOpen, option, setIsOpen, setOption }}>
오호 이렇게 하는 방법이 있었네요 !!
코드가 좀 더 간결해졌어요 👍

2024-04-11 12:01 UTC, Februaar commented
> @Februaar Omit 관련해서 고민을 작성해주셨네요. Pick, Omit은 어떤 경우에 사용하게 될까요?

Pick 유틸리티는 특정 타입에서 지정된 속성만을 선택하여 새로운 타입을 만드는 것이고, Omit 유틸리티는 지정된 속성을 제외하고 나머지 속성을 가지고 새로운 타입을 만들어주는 것으로 정리해봤습니다!

2024-04-13 15:10 UTC, Februaar commented
### 수정내역

- theme으로 정의하는 디자인 토큰은 공용으로 사용되는 값으로만 관리하도록 수정
- 레이어별 우선순위 부여하기 위해 zIndex 값 토큰화
- 상수 코드 컨벤션 camelCase로 일관성 부여

**Select 컴포넌트**
- _윗 방향 화살표_ 아이콘 제거
- Select 컴포넌트의 open 이벤트 동작에 대한 setIsOpen 상태 값을 다룸 => openSelect, closeSelect 함수 생성해서 직관적인 값을 다루도록 리팩토링
- onMouseDown으로 이벤트 동작이 일어나면 선택된 값은 SelectTrigger로 전달하도록 기능 구현
- 컴포넌트 이름에 prefix 추가

2024-04-26 16:23 UTC, bytrustu approved these changes
리뷰가 많이 늦었네요. 😭
몇가지 학습해보면 좋을 내용으로 제안드렸습니다.

고생 많으셨어요!! 👏

2024-04-26 16:23 UTC, bytrustu commented on src/components/Button/Button.utils.ts
> +  const colorProps = color ? buttonColorType[color] : null;
P3:

size, color props의 초기 값을 지정하면 어떨까요?

```tsx
export const getButtonStyles = ({
  size = 'md',
  color = 'gray',
  ...
}: ButtonProps) => {
  const sizeProps = buttonTypebySize[size];
  const colorProps = buttonColorType[color];
}
```

2024-04-26 16:23 UTC, bytrustu commented on src/components/Modal/Modal.styles.tsx
> +  z-index: ${theme.zIndex.overlay};
zIndex 값을 토큰으로 분류해준 점이 좋네요 👍
지금과 같이 관리한다면, 레이어 영역의 우선순위를 잘 관리할 수 있을거예요.

2024-04-26 16:23 UTC, bytrustu commented on src/components/Select/Select.hooks.ts
> +  const [option, setOption] = useState<string>("");
P3:

useState에 타입을 지정하지 않더라도  
초기 값 `false` `""` 을 통해 타입추론이 되지 않을까요?

타입 추론이 가능한 영역이라면 꼭 타입을 명시적으로 작성해줄 필요는 없겠어요.
어떤 경우에 타입선언이 필요하고, 어떤 경우엔 타입추론으로 가능할지 고민해보면 좋겠어요.
이펙티브 타입스크립트 책이 있으시면, 타입추론 파트도 읽어보시면 도움 되시겠네요!

2024-04-26 16:23 UTC, bytrustu commented on src/styles/theme/zIndex.ts
> +export const zIndex = {
P3:

theme는 default export, zIndex는 named export 로 선언 되어있네요.
경진님의 모듈을 내보내는 기준이 있을까요?

https://lasbe.tistory.com/187#google_vignette
https://www.npmjs.com/package/barrelsby

링크를 한번 보셔도 좋겠네요!

2024-04-26 16:23 UTC, bytrustu commented on src/components/Select/Select.hooks.ts
> +  }, [value]);
P3:

초기값을 반영하기 위함이라면, useState에 option value를 반영해도 되지 않을까요?

2024-04-26 16:25 UTC, bytrustu commented
@Februaar 
PR은 머지하겠습니다.
마지막 제안드린 리뷰는 따로 학습해보시면 좋겠어요. 😁

2024-04-26 16:25 UTC, merged

2024-04-27 10:16 UTC, Februaar commented on src/components/Modal/Modal.styles.tsx
> +  z-index: ${theme.zIndex.overlay};
이전에는 z-index에 무분별하게 우선순위를 부여했다면,
zIndex 값을 토큰화 해주니까 좀 더 명확하게 관리되는 것 같아요!

2024-04-27 10:29 UTC, Februaar commented on src/components/Button/Button.utils.ts
> +  const colorProps = color ? buttonColorType[color] : null;
npm에 배포하고 테스트 하는 과정에서 초기 값이 지정되어 있지 않아
사용에 불편함을 인지하고 바로 수정했습니다!

2024-04-27 11:15 UTC, Februaar commented on src/components/Select/Select.hooks.ts
> +  const [option, setOption] = useState<string>("");
넵 이 부분도 꼭 정리해봐야겠어요!

항상 명확한 의미가 있는 코드를 작성하도록 🔥